 const CartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_CART_ITEM: 'CLEAR_CART_ITEM',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    CLEAR_CART_OUT_SUCCESS: 'CLEAR_CART_OUT_SUCCESS'
}

export default CartActionTypes;